version: "3.9"

services:
  
  kaggle_tabular_playground:
    build: .
    image: kaggle_tabular_playground
    container_name: kaggle_tabular_playground
    environment:
      - PASSWORD=nfl
      - USERID=${xUID}
    ports:
      - "8795:8787"
    restart: always
    volumes:
      - .:/home/rstudio/project