stages:
  prepare_data:
    cmd: Rscript prepare_data.R
    deps:
      - prepare_data.R
      - functions/clean_data.R
      - data/train.csv
    outs: 
      - outputs/train_fold.rds
      - outputs/validation_fold.rds
  train_model:
    cmd: Rscript train_model.R
    deps:
      - train_model.R
      - outputs/train_fold.rds
      - outputs/validation_fold.rds
    outs:
      - outputs/machine_state_model.rds
    metrics:
      - metrics/roc.txt:
          cache: false
  train_rf_model:
    cmd: Rscript train_rf_model.R
    deps:
      - train_rf_model.R
      - outputs/train_fold.rds
      - outputs/validation_fold.rds
    outs:
      - outputs/machine_state_rf_model.rds
    metrics:
      - metrics/rf_roc.txt:
          cache: false
  get_predictions:
    cmd: Rscript get_predictions.R
    deps:
      - get_predictions.R
      - outputs/machine_state_model.rds
      - outputs/machine_state_rf_model.rds
      - data/test.csv
    outs:
      - outputs/submission_data.csv