stages:
  prepare_data:
    cmd: Rscript prepare_data.R
    deps:
    - prepare_data.R
    - data/train.csv
    outs: 
    - train_fold.rds
    - validation_fold.rds
  train_model:
    cmd: Rscript train_model.R
    deps:
    - train_model.R
    - train_fold.rds
    - validation_fold.rds
    outs:
    - rpart_model.rds
    metrics:
    - accuracy.txt