stages:
  prepare_data:
    cmd: Rscript prepare_data.R
    deps:
    - prepare_data.R
    - data/train.csv
    outs: 
    - outputs/train_fold.rds
    - outputs/validation_fold.rds
  train_model:
    cmd: Rscript train_model.R
    deps:
    - train_model.R
    - outputs/train_fold.rds
    - outputs/validation_fold.rds
    outs:
    - outputs/machine_state_model.rds
  get_predictions:
    cmd: Rscript get_predictions.R
    deps:
    - outputs/machine_state_model.rds
    - data/test.csv
    outs:
    - outputs/submission_data.csv